#!/bin/bash

# Set defaults
prefix="${PREFIX:=${HOME}/installed}"
tag="${TAG:=v8.2.0}"

set -e


function usage()
{
    cat << EOF


  Usage: $0 [[[-]-prefix[=]| ]PREFIX] [TAG]

   Install nodeJS from the github source.

    
  ---------------- OPTIONS -------------------------

    -prefix PREFIX  Set the installation prefix directory.
          Don't include a trailing '/'.   The default prefix
          is $prefix

    TAG   pick a particular git tag of the source to install.
          The default tag is $tag

EOF
    exit 1
}


while [ -n "$1" ] ; do

    case "$1" in

        -h*|--h*)
            usage
            ;;
        -prefix|--prefix)
            shift 1
            [ -z "$1"] && usage
            prefix="$1"
            ;;
        -prefix=*|--prefix=*)
            prefix="${1##*-prefix=}"
            ;;
        *)
            tag="$1"
            ;;
    esac
    shift
done


set -x
set -o pipefail

mkdir BUILD_nodejs
cd BUILD_nodejs

path=nodejs/node

wget -O - https://github.com/$path/tarball/$tag | tar -xvz

cd nodejs-node*

./configure --prefix=$prefix
make -j$(nproc)
make install

